#!/bin/bash

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

clear

echo -e "${CYAN}"
cat << "EOF"
╔═══════════════════════════════════════════════════════════════╗
║                                                               ║
║        Artists & Albums API - Senior Backend Project         ║
║                                                               ║
║                    Java | Spring Boot | REST                 ║
║                                                               ║
╚═══════════════════════════════════════════════════════════════╝
EOF
echo -e "${NC}"

echo ""
echo -e "${YELLOW}═══ PROJECT INFORMATION ═══${NC}"
echo "Framework: Spring Boot 3.3"
echo "Language: Java 17"
echo "Database: PostgreSQL 16"
echo "Storage: MinIO (S3-compatible)"
echo "Containerization: Docker & Docker Compose"

echo ""
echo -e "${YELLOW}═══ REQUIREMENTS STATUS ═══${NC}"
echo -e "${GREEN}✓${NC} Requisitos Gerais (12/12)"
echo -e "${GREEN}✓${NC} Requisitos Sênior (5/5)"
echo -e "${GREEN}✓${NC} Total: 17/17 ✓✓✓"

echo ""
echo -e "${YELLOW}═══ KEY FEATURES ═══${NC}"
echo -e "${GREEN}✓${NC} JWT Authentication (5 min expiration + refresh)"
echo -e "${GREEN}✓${NC} Rate Limiting (10 req/min per user)"
echo -e "${GREEN}✓${NC} WebSocket Notifications (Real-time albums)"
echo -e "${GREEN}✓${NC} MinIO Integration (Presigned URLs, 30 min expiry)"
echo -e "${GREEN}✓${NC} CORS Security (Domain blocking)"
echo -e "${GREEN}✓${NC} Pagination (All endpoints)"
echo -e "${GREEN}✓${NC} Health Checks (Liveness + Readiness)"
echo -e "${GREEN}✓${NC} Regional Sync (External API integration)"
echo -e "${GREEN}✓${NC} OpenAPI/Swagger (Interactive docs)"
echo -e "${GREEN}✓${NC} Unit Tests (JUnit 5 + Mockito)"

echo ""
echo -e "${YELLOW}═══ QUICK START ═══${NC}"
echo ""
echo -e "  ${CYAN}Option 1: Docker Compose (Recommended)${NC}"
echo "    $ docker-compose up -d"
echo "    → API: http://localhost:8080/api"
echo "    → Swagger: http://localhost:8080/api/swagger-ui.html"
echo "    → MinIO: http://localhost:9001"
echo ""
echo -e "  ${CYAN}Option 2: Local with Maven${NC}"
echo "    $ mvn clean package"
echo "    $ java -jar target/artists-api-1.0.0.jar"
echo ""
echo -e "  ${CYAN}Option 3: Using Make${NC}"
echo "    $ make docker-up"
echo "    $ make logs"

echo ""
echo -e "${YELLOW}═══ CREDENTIALS ═══${NC}"
echo "API:"
echo "  username: admin"
echo "  password: admin"
echo ""
echo "MinIO:"
echo "  username: minioadmin"
echo "  password: minioadmin"

echo ""
echo -e "${YELLOW}═══ PROJECT STRUCTURE ═══${NC}"
cat << "EOF"
src/main/java/com/artists/
├── api/                  → REST Controllers & DTOs
├── application/          → Business Logic Services
├── domain/              → JPA Entities
├── infrastructure/      → Repositories & Config
└── presentation/        → WebSocket Handlers

Resources:
├── application.yml      → Configuration
├── db/migration/        → Flyway SQL Scripts
└── endpoints →25+ REST endpoints (documented in Swagger)
EOF

echo ""
echo -e "${YELLOW}═══ API ENDPOINTS ═══${NC}"
echo ""
echo -e "${BLUE}Authentication${NC}"
echo "  POST /v1/auth/login              - Login & get JWT tokens"
echo "  POST /v1/auth/refresh            - Refresh access token"
echo ""
echo -e "${BLUE}Artists${NC}"
echo "  GET  /v1/artists                 - List (paginated)"
echo "  GET  /v1/artists/{id}            - Get by ID"
echo "  GET  /v1/artists/search          - Search with sorting"
echo "  POST /v1/artists                 - Create (authenticated)"
echo "  PUT  /v1/artists/{id}            - Update (authenticated)"
echo "  DELETE /v1/artists/{id}          - Delete (authenticated)"
echo ""
echo -e "${BLUE}Albums${NC}"
echo "  GET  /v1/albums                  - List (paginated)"
echo "  GET  /v1/albums/{id}             - Get by ID"
echo "  GET  /v1/albums/search           - Search by title"
echo "  GET  /v1/albums/artist/{id}      - List by artist"
echo "  POST /v1/albums                  - Create (authenticated)"
echo "  PUT  /v1/albums/{id}             - Update (authenticated)"
echo "  POST /v1/albums/{id}/images      - Upload images (authenticated)"
echo "  DELETE /v1/albums/{id}           - Delete (authenticated)"
echo ""
echo -e "${BLUE}Regionais${NC}"
echo "  GET  /v1/regionais               - List active"
echo "  GET  /v1/regionais/all           - List all"
echo "  POST /v1/regionais/sync          - Manual sync (authenticated)"
echo ""
echo -e "${BLUE}Health${NC}"
echo "  GET  /v1/health                  - Full health check"
echo "  GET  /v1/health/live             - Liveness probe"
echo "  GET  /v1/health/ready            - Readiness probe"

echo ""
echo -e "${YELLOW}═══ TESTING ENDPOINTS ═══${NC}"
echo ""
echo "  # Login"
echo "  curl -X POST http://localhost:8080/api/v1/auth/login \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"username\":\"admin\",\"password\":\"admin\"}'"
echo ""
echo "  # List Artists"
echo "  curl http://localhost:8080/api/v1/artists?page=0&size=10"
echo ""
echo "  # Search Artists"
echo "  curl 'http://localhost:8080/api/v1/artists/search?name=Serj&sort=asc'"
echo ""
echo "  # Create Album (requires JWT)"
echo "  curl -X POST http://localhost:8080/api/v1/albums \\"
echo "    -H 'Authorization: Bearer \$TOKEN' \\"
echo "    -H 'Content-Type: application/json' \\"
echo "    -d '{\"title\":\"My Album\",\"releaseYear\":2024}'"

echo ""
echo -e "${YELLOW}═══ DOCUMENTATION FILES ═══${NC}"
echo "  📖 README.md              - Complete documentation"
echo "  ⚡ QUICK_START.md         - 5-minute setup"
echo "  🏗️  ARCHITECTURE.md        - System architecture"
echo "  📝 CONTRIBUTING.md        - Development guidelines"
echo "  🚀 DEPLOYMENT.md          - Production deployment"
echo "  📊 PROJECT_SUMMARY.md     - Project overview"

echo ""
echo -e "${YELLOW}═══ USEFUL COMMANDS ═══${NC}"
echo ""
echo -e "  ${CYAN}Docker${NC}"
echo "    docker-compose up -d              Start all services"
echo "    docker-compose down               Stop all services"
echo "    docker-compose logs -f api        View API logs"
echo ""
echo -e "  ${CYAN}Maven${NC}"
echo "    mvn clean package                 Build project"
echo "    mvn test                          Run tests"
echo "    mvn spring-boot:run               Run locally"
echo ""
echo -e "  ${CYAN}Make${NC}"
echo "    make help                         Show all targets"
echo "    make build                        Build project"
echo "    make test                         Run tests"
echo "    make docker-up                    Start Docker"
echo "    make logs                         View logs"
echo ""
echo -e "  ${CYAN}Database${NC}"
echo "    postgres://localhost:5432/artists_db"
echo "    User: postgres | Password: postgres"
echo ""
echo -e "  ${CYAN}MinIO${NC}"
echo "    http://localhost:9001             Console"
echo "    http://localhost:9000             API"

echo ""
echo -e "${YELLOW}═══ TECHNOLOGIES STACK ═══${NC}"
echo ""
echo -e "  ${CYAN}Core${NC}"
echo "    • Spring Boot 3.3.0"
echo "    • Spring Web, Data JPA, Security"
echo "    • Spring WebSocket"
echo "    • Spring Actuator (Health checks)"
echo ""
echo -e "  ${CYAN}Database${NC}"
echo "    • PostgreSQL 16 (HikariCP)"
echo "    • Flyway (Migrations)"
echo ""
echo -e "  ${CYAN}Security${NC}"
echo "    • JWT (JJWT)"
echo "    • CORS"
echo "    • Rate Limiting (Google Guava)"
echo ""
echo -e "  ${CYAN}Integration${NC}"
echo "    • MinIO (S3-compatible)"
echo "    • WebSocket"
echo "    • External APIs (Regionais)"
echo ""
echo -e "  ${CYAN}Documentation${NC}"
echo "    • Springdoc OpenAPI"
echo "    • Swagger UI"
echo ""
echo -e "  ${CYAN}Testing${NC}"
echo "    • JUnit 5"
echo "    • Mockito"
echo ""
echo -e "  ${CYAN}DevOps${NC}"
echo "    • Docker"
echo "    • Docker Compose"
echo "    • Kubernetes-ready"

echo ""
echo -e "${YELLOW}═══ FILE STRUCTURE ═══${NC}"
echo ""
echo "  artists-api/"
echo "  ├── src/main/java/com/artists/"
echo "  │   ├── api/                (Controllers, DTOs)"
echo "  │   ├── application/        (Services)"
echo "  │   ├── domain/             (Entities)"
echo "  │   ├── infrastructure/     (Repositories, Config)"
echo "  │   └── presentation/       (WebSocket)"
echo "  ├── src/main/resources/"
echo "  │   ├── application.yml"
echo "  │   └── db/migration/       (SQL Scripts)"
echo "  ├── src/test/java/          (Unit Tests)"
echo "  ├── pom.xml                 (Maven Config)"
echo "  ├── Dockerfile              (Container Image)"
echo "  ├── docker-compose.yml      (Orchestration)"
echo "  ├── Makefile                (Build Commands)"
echo "  └── *.md                    (Documentation)"

echo ""
echo -e "${YELLOW}═══ INITIAL DATA ═══${NC}"
echo ""
echo "  Artists (4):"
echo "    • Serj Tankian"
echo "    • Mike Shinoda"
echo "    • Michel Teló"
echo "    • Guns N' Roses"
echo ""
echo "  Albums (13):"
echo "    • Harakiri, Black Blooms, The Rough Dog"
echo "    • The Rising Tied, Post Traumatic, Post Traumatic EP, Where'd You Go"
echo "    • Bem Sertanejo, Bem Sertanejo - O Show (Ao Vivo), Bem Sertanejo - EP"
echo "    • Use Your Illusion I, Use Your Illusion II, Greatest Hits"

echo ""
echo -e "${YELLOW}═══ NEXT STEPS ═══${NC}"
echo ""
echo "  1️⃣  Start Docker Compose:"
echo "     $ docker-compose up -d"
echo ""
echo "  2️⃣  Wait for services to be ready (~30 seconds)"
echo ""
echo "  3️⃣  Test the API:"
echo "     $ curl http://localhost:8080/api/v1/artists"
echo ""
echo "  4️⃣  Access Swagger UI:"
echo "     → http://localhost:8080/api/swagger-ui.html"
echo ""
echo "  5️⃣  Read documentation:"
echo "     → README.md (complete guide)"
echo "     → QUICK_START.md (5-minute setup)"
echo "     → ARCHITECTURE.md (system design)"

echo ""
echo -e "${GREEN}═══ PROJECT READY FOR DEPLOYMENT ═══${NC}"
echo ""
echo -e "${CYAN}All requirements implemented ✓${NC}"
echo ""
echo "For support, check:"
echo "  • README.md"
echo "  • ARCHITECTURE.md"
echo "  • CONTRIBUTING.md"
echo "  • Swagger UI at http://localhost:8080/api/swagger-ui.html"
echo ""
echo -e "${CYAN}Built with ❤️  using Spring Boot, Docker, PostgreSQL and MinIO${NC}"
echo ""
